"""empty message

Revision ID: bac57a5be190
Revises: 9d83be9bcd94
Create Date: 2019-09-06 18:16:59.719767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac57a5be190'
down_revision = '9d83be9bcd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'location', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
